service: project-sls
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2
  apiGateway:
    shouldStartNameWithService: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-west-2:031392238163:table/productsTable

plugins:
  - serverless-offline

functions:
  createProduct:
    handler: src/handler.createProduct
    events:
      - httpApi:
          method: POST
          path: /products
  getProducts:
    handler: src/handler.getProducts
    events:
      - httpApi:
          method: GET
          path: /products
  getProduct:
    handler: src/handler.getProduct
    events:
      - httpApi:
          method: GET
          path: /products/{id}
  deleteProduct:
    handler: src/handler.deleteProduct
    events:
      - httpApi:
          method: DELETE
          path: /product
  updateProduct:
    handler: src/handler.updateProduct
    events:
      - httpApi:
          method: PUT
          path: /products/{id}

resources:
  Resources:
    productsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: productsTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST